#!/bin/sh
cd ~
if [ -s .bashrc -a ! -s .bashrc.backup ]
then
	mv .bashrc .bashrc.backup
	sed -e "/^#force_color_prompt/s/#//" -e "/debian.*033/s/'[^']*/'"'\\[\\033[01;32m\\]\\!\\[\\033[00m\\] \\[\\033[01;34m\\]\\w\\[\\033[00m\\]$ /' .bashrc.backup > .bashrc
fi
sed -e "s/^    /\t\t\t\t/" -e "s/^   /\t\t\t/" -e "s/^  /\t\t/" -e "s/^ /\t/" > .bash_aliases <<- EOF
	cd_() {
	 "cd" "\$@" && ls --color=auto -F
	}
	pd_() {
	 pushd "\$@" && ls --color=auto -F
	}
	pp_() {
	 popd "\$@" && ls --color=auto -F
	}
	alias cd=cd_
	alias md=mkdir
	alias pd=pd_
	alias pp=pp_
	alias rd=rmdir
	alias b='cd ..'
	alias j=jobs
	alias h=history
	alias gh='history | grep'
	alias ls='ls --color=auto -F'
	alias ll='ls -l'
	alias la='ls -A'
	alias lal='la -l'
	alias gcm='git commit -m'
	alias gd='git diff'
	alias gl='git log --name-status'
	alias gs='git status -s'
	export PYTHONPATH=~/lib
EOF
cat > .vimrc <<- EOF
	map <C-n> :set nu<CR>
	map <C-p> :set nonu<CR>
	map gc :wa<CR>:!g++ -std=c++11 % && ./a.out
	map gh :wa<CR>:!python3 % --help<CR>
	map gj :wa<CR>:!./%<CR>
	map gl :ls<CR>
	map gp :wa<CR>:!python3 % --test<CR>
	map gq :wa<CR>:!psql -f %<CR>
	map gw :wa<CR>
	set ai
	set background=dark
	set sw=4
	set ts=4
	syntax on
	filetype indent plugin on
	autocmd FileType python setlocal expandtab softtabstop=2 sw=2 ts=2
EOF
