#!/bin/sh
cp .bash_aliases .vimrc $HOME
cd $HOME
if [ -s .bashrc -a ! -s .bashrc.backup ]; then
	cp -p .bashrc .bashrc.backup
	if grep -q force_color_prompt .bashrc; then
		sed -e "/^#force_color_prompt/s/#//" -e "/debian.*033/s/'[^']*/'"'\\[\\033[01;32m\\]\\!\\[\\033[00m\\] \\[\\033[01;34m\\]\\w\\[\\033[00m\\]$ /' .bashrc > .bashrc.tmp
		mv .bashrc.tmp .bashrc
	fi
	grep -q PYTHONPATH .bashrc || echo "export PYTHONPATH=~/lib" >> .bashrc
fi
if [ -f .zshrc ]; then
	mv .bash_aliases .zsh_aliases
	echo 'source .zsh_aliases' >> .zshrc
else
	echo 'source .bash_aliases' >> .bashrc
fi
