#!/bin/sh
cd ~
if [ ! -s .bashrc.backup ]
then
	mv .bashrc .bashrc.backup
	sed -e "/^#force_color_prompt/s/#//" -e "/debian.*033/s/'[^']*/'"'\\[\\033[01;32m\\]\\!\\[\\033[00m\\] \\[\\033[01;34m\\]\\w\\[\\033[00m\\]$ /' .bashrc.backup > .bashrc
fi
sed "s/^ /	/" > .bash_aliases <<- EOF
	cd_() {
	 "cd" "\$@" && ls --color=auto -F
	}
	pd_() {
	 pushd "\$@" && ls --color=auto -F
	}
	pp_() {
	 popd "\$@" && ls --color=auto -F
	}
	alias cd=cd_
	alias md=mkdir
	alias pd=pd_
	alias pp=pp_
	alias rd=rmdir
	alias b='cd ..'
	alias j=jobs
	alias h=history
	alias ls='ls --color=auto -F'
	alias ll='ls -l'
	alias la='ls -A'
	alias lal='la -l'
	alias gcm='git commit -m'
	alias gd='git diff'
	alias gs='git status -s'
	export PYTHONPATH=~/lib
EOF
cat > .vimrc <<- EOF
	map  :set nu
	map  :set nonu
	map gh :w:!python3 % --help
	map gj :w:!./%
	map gp :w:!python3 % --test
	set ai
	set sw=4
	set ts=4
	filetype plugin indent on
	autocmd FileType python setlocal shiftwidth=2 softtabstop=2 expandtab
EOF
